service: w3z

frameworkVersion: "=1.54.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

# stage: ${env:NODE_ENV}
region: us-east-1

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{converted_url+}
          method: get
