#    docs.serverless.com
service: w3z-serverless

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true

